image: Ubuntu

install:
  - mkdir /dev/shm/mysql
  - ls -al /var/lib/mysql
  - sudo ln -s /dev/shm/mysql /var/lib/mysql

before_build:

services:
  - mysql
test_script:
  - id
  - df -h
  - free -m
  - ls -al /dev/shm/mysql
  - mysql -uroot -pPassword12! -e 'SHOW VARIABLES WHERE Variable_Name LIKE "%dir"'
  
