image: Ubuntu

init:
  - sudo cat /etc/mysql/mysql.conf.d/mysqld.cnf
  - sudo sed -i 's!/var/lib/mysql!/dev/shm/mysql!' /etc/apparmor.d/usr.sbin.mysqld
  - sudo cat /etc/apparmor.d/usr.sbin.mysqld
  - sudo cp -rp /var/lib/mysql /dev/shm
  - sudo ls -al /dev/shm/mysql
  - sudo mv /var/lib/mysql /var/lib/mysql.local
  - sudo ln -s /dev/shm/mysql /var/lib/mysql
  - sudo ls -al /var/lib/mysql

before_build:

services:
  - mysql

test_script:
  - id
  - df -h
  - free -m
  - ls -al /dev/shm/mysql
  - mysql -uroot -pPassword12! -e 'SHOW VARIABLES WHERE Variable_Name LIKE "%dir"'
  
