image: Ubuntu

init:
  - sudo service mysql status
  - mkdir /dev/shm/mysql
  - sudo cp -r /var/lib/mysql/* /dev/shm/mysql
  - sudo chown -R mysql:mysql /dev/shm/mysql
  - sudo ls -al /dev/shm/mysql
  - sudo mv /var/lib/mysql /var/lib/mysql.local
  - sudo ln -s /dev/shm/mysql /var/lib/mysql

before_build:

services:
  - mysql
test_script:
  - id
  - df -h
  - free -m
  - ls -al /dev/shm/mysql
  - mysql -uroot -pPassword12! -e 'SHOW VARIABLES WHERE Variable_Name LIKE "%dir"'
  
