image: Ubuntu
before_build:
services:
  - mysql
test_script:
  - id
  - df -h
  - free -m
  - mkdir /dev/shm/mysql
  - ls -al /dev/shm
  - mysql -uroot -pPassword12! -e 'SHOW VARIABLES WHERE Variable_Name LIKE "%dir"'
  
